# Generated by Django 3.1.4 on 2021-01-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0003_auto_20201222_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='funcionarios/imagens'),
        ),
    ]
