# Generated by Django 3.1.4 on 2020-12-21 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_auto_20201221_1531'),
        ('documentos', '0002_documento_dono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='dono',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='funcionarios.funcionario'),
            preserve_default=False,
        ),
    ]
