# Generated by Django 3.1.4 on 2020-12-29 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0008_auto_20201229_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='documentos/imagens'),
        ),
    ]
